
const SUPABASE_URL = 'https://hqonnxnwozfwkpqgabpf.supabase.co';
const SUPABASE_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imhxb25ueG53b3pmd2twcWdhYnBmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzgwNzYwODgsImV4cCI6MjA5MzY1MjA4OH0.GZjxRoJvc7k1EeRiZ8n6JX6T-tWD7Jy7q_bKHqYwdqU';

const rawData = `
1	ADRYAN JOSÉ RIBEIRO ZAGHI	6º ANO A	Ativo
2	ALICY YASMYN SAAB CABRAL DE REZENDE SANTANA	6º ANO A	Ativo
3	ANNA JÚLIA FERREIRA	6º ANO A	Ativo
4	ANTONIA PACHECO BARBOSA DOS SANTOS	6º ANO A	Ativo
5	ARTHUR AUBRY PELEGRINI HERNANDES	6º ANO A	Ativo
6	ARTHUR LOBO PEREIRA EONCONI	6º ANO A	Ativo
7	CARLOS EDUARDO MACÊDO FERREIRA	6º ANO A	Ativo
8	CARLOS HENRIQUE MOREIRA PALANCIO	6º ANO A	Ativo
9	DANIEL HENRIQUE GONÇALVES SOVERNIGO	6º ANO A	Ativo
10	DIEGO NOGUEIRA FOGAÇA	6º ANO A	Ativo
11	EDUARDO DA CRUZ CORRÊA NETO	6º ANO A	Ativo
12	EMANUEL DAVI CORRÊA DE ALMEIDA BARBOSA	6º ANO A	Ativo
13	EMANUELLY SOUZA SILVA	6º ANO A	Ativo
14	GABRIEL DA SILVA ANTUNES	6º ANO A	Ativo
15	GABRIEL SILVA SANTELA	6º ANO A	Ativo
16	GUILHERME RODRIGUES COSTA	6º ANO A	Ativo
17	GUSTAVO FRANCOLINO FRANÇA	6º ANO A	Ativo
18	ISABELLY FERNANDES LIMA	6º ANO A	Ativo
19	JOÃO GABRIEL BARBOSA MARTINS	6º ANO A	Ativo
20	JOSÉ GABRIEL MACHADO VALDEZ CHAGAS	6º ANO A	Ativo
21	LETICIA WEILLER MOURA	6º ANO A	Ativo
22	LUIZ ANTONIO DOS SANTOS RIBEIRO	6º ANO A	Ativo
23	MARCELA ANGELO CARDOSO DE MOURA	6º ANO A	Ativo
24	MARIA HELOISA NASCIMENTO BARBOSA	6º ANO A	Ativo
25	MIGUEL LINO DOS SANTOS KINOSITA	6º ANO A	Ativo
26	MILENA MEDEIRO LIMA	6º ANO A	Ativo
27	MIRELLA DE SOUZA CONCEIÇÃO	6º ANO A	Ativo
28	RAY FELIPE BATISTA GOMES	6º ANO A	Ativo
29	SARA DIAS DE ALMEIDA	6º ANO A	Ativo
30	SOFIA BARBOSA BORGES DA SILVA	6º ANO A	Ativo
31	SOFIA BEATRIZ DA SILVA RIBEIRO	6º ANO A	Ativo
32	VINICIUS FERREIRA RODRIGUES	6º ANO A	Ativo
33	BEATRIZ SILVA CIMATTI	6º ANO A	Ativo
34	JOÃO MIGUEL ANASTACIO DE ASSIS	6º ANO A	Ativo
35	ISABELLY VITÓRIA MELGAR RIBEIRO	6º ANO A	Ativo
36	YASMIN VALENTINA PINHEIRO DA SILVA	6º ANO A	Ativo
1	ANA CARLA BATISTA NASCIMENTO	7º ANO A	Ativo
2	ARON TALGATTI DOS SANTOS	7º ANO A	Ativo
3	BRENDA DE OLIVEIRA ROCHA	7º ANO A	Ativo
4	BRENO GUSTAVO VALEJO DA SILVA	7º ANO A	Ativo
5	BRUNO GABRIEL NASCIMENTO DE ALMEIDA	7º ANO A	Ativo
6	CLARA VITÓRIA VIEIRA GIMENEZ DE CARVALHO	7º ANO A	Ativo
7	DANILO NUNES DOS SANTOS	7º ANO A	Ativo
8	EMANUELLY LIMA DA SILVA DE SOUZA	7º ANO A	Ativo
9	EMILI DE DEUS DA SILVA	7º ANO A	Ativo
10	ESTEFANY VIEIRA RODRIGUES	7º ANO A	Ativo
11	GIOVANI COURA DE CASTRO	7º ANO A	Ativo
12	GUILHERME DENIZ DE FREITAS	7º ANO A	Ativo
13	HENRIQUE  ECHEVERRIA DE MATOS	7º ANO A	Ativo
14	IRIS DALIANA NOGUEIRA DOS SANTOS	7º ANO A	Ativo
15	ISADORA JULIA BRITO DE SOUZA	7º ANO A	Ativo
16	JAQUELYNE LINCHE DE OLIVEIRA	7º ANO A	Ativo
17	JOÃO GABRIEL FERNANDES DUDU FERREIRA	7º ANO A	Ativo
18	JOÃO PAULO GONÇALVES PEREIRA	7º ANO A	Ativo
19	JOSÉ MARIA DOS SANTOS NETO	7º ANO A	Ativo
20	LAVÍNIA CASSIMIRO DEL GRANDE	7º ANO A	Ativo
21	LAYS BÁRBARA RODRIGUES ARRUDA	7º ANO A	Ativo
22	MARIANA ROMERO OVANDO	7º ANO A	Ativo
23	MIGUEL PALAZZINI DE BRITO CARDOSO SANTOS	7º ANO A	Ativo
24	NATAN LUCAS DA SILVA GENEROSO	7º ANO A	Ativo
25	NATHALY GABRIELY GALVÃO DUARTE	7º ANO A	Ativo
26	OLAVO SOUZA MEDINA	7º ANO A	Ativo
27	PEDRO LIMA FLORES	7º ANO A	Ativo
28	RENATO AUGUSTO CONSOLARO DE OLIVEIRA	7º ANO A	Ativo
29	VICTOR HUGO BENITES PEREIRA SILVA	7º ANO A	Ativo
30	YAHN KALLEB BARBOSA DE OLIVEIRA	7º ANO A	Ativo
31	SOFIA MARQUES FERRAZ	7º ANO A	Ativo
1	AGHATA MERIÊ PEIXOTO VILLALBA	8º ANO A	Ativo
2	ALICE DE LARA WIDER	8º ANO A	Ativo
3	ALICE DE OLIVEIRA BARRETO	8º ANO A	Ativo
4	ANA CLARA ALMEIDA DOS SANTOS	8º ANO A	Ativo
5	ANA GABRIELLA DO ROSARIO BORGES	8º ANO A	Ativo
6	BEATRIZ CHAVES TAVARES	8º ANO A	Ativo
7	BEATRIZ FERNANDA OLIVEIRA	8º ANO A	Ativo
8	BRUNO HENRIQUE DE SOUZA	8º ANO A	Ativo
9	BRUNO VINÍCIUS SERRA NOSTÓRIO	8º ANO A	Ativo
10	DAFNI VITÓRIA CAETANO FINAMOR	8º ANO A	Ativo
11	DAVI FERNANDES DE ALMEIDA PRADO	8º ANO A	Ativo
12	DAVI GONÇALVES IRALA	8º ANO A	Ativo
13	EMANUELLY CLAVICO NEVES	8º ANO A	Ativo
14	EMILLY ESTER SANTANA MEDINA	8º ANO A	Ativo
15	EMILLY GABRIELE DA SILVA MIRANDA	8º ANO A	Ativo
16	EMILY NOGUEIRA ELICHESE	8º ANO A	Ativo
17	GABRIELLY MESQUITA	8º ANO A	Ativo
18	GERSON PEREIRA SILVA NETO	8º ANO A	Ativo
19	HELLOISE KARINY ALMEIDA PARREIRA DA SILVA	8º ANO A	Ativo
20	HENZO ALMEIDA DA SILVA	8º ANO A	Ativo
21	ISABELLA BRITO DIAS	8º ANO A	Ativo
22	LAIZ GABRIELLY DOS SANTOS BATISTA	8º ANO A	Ativo
23	LAUREN CABRIOTI ANDRADE BARROS	8º ANO A	Ativo
24	LUIZ MIGUEL FLORENTIN GARCETE	8º ANO A	Ativo
25	MARIA EDUARDA MOURA SANTOS	8º ANO A	Ativo
26	MARIA EDUARDA NÓBREGA COLOMBO	8º ANO A	Ativo
27	MIGUEL SILVA SANTELA	8º ANO A	Ativo
28	NATHALLY AREVALOS DIAS	8º ANO A	Ativo
29	NICOLE GUTIERREZ NICOLAU	8º ANO A	Ativo
30	PEDRO GUILHERME FRANÇA VIEIRA	8º ANO A	Ativo
31	POLIANA CARDOSO LEITE	8º ANO A	Ativo
32	SARAH SOUZA DE OLIVEIRA	8º ANO A	Ativo
33	SHAHARAZADE CRISTINA APARECIDA NOGUEIRA MOTTA PINTO	8º ANO A	Ativo
34	SUELLEN SANTOS NASCIMENTO BARBOSA	8º ANO A	Ativo
35	SUZANY DAIREN BENITES SANTOS	8º ANO A	Ativo
36	THIAGO ANTUNES DA SILVA	8º ANO A	Ativo
37	WESLLEY RAFAEL FERREIRA	8º ANO A	Ativo
38	EMANUEL LIMA DA SILVA MARECO	8º ANO A	Ativo
39	GUILHERME SILVA CIMATTI	8º ANO A	Ativo
40	LEONARDO MOREIRA RODRIGUES	8º ANO A	Ativo
1	ÁGATA RODRIGUES DA SILVA	9º ANO A	Ativo
2	AGHATA MELLYSSA DUARTE PAIVA	9º ANO A	Ativo
3	ANA JULLYA AZEVEDO PRADO	9º ANO A	Ativo
4	ANA ORTIZ DE SOUZA FERREIRA	9º ANO A	Ativo
5	ARTHUR ESCRIVANO GONÇALVES	9º ANO A	Ativo
6	ASAFE SERAFIM SALES	9º ANO A	Ativo
7	BETINA BATISTA DE SOUZA	9º ANO A	Ativo
8	CARLOS HENRIQUE AUBRY PELEGRINI DOS SANTOS	9º ANO A	Ativo
9	CARLOS HENRIQUE DE OLIVEIRA PORTELA	9º ANO A	Ativo
10	CLARA HORING DUARTE	9º ANO A	Ativo
11	COLLYNS GABRIEL SOARES PUERARI	9º ANO A	Ativo
12	ELIAS MIGUEL NUNES CORREA	9º ANO A	Ativo
13	GEOVANNA BARBOSA DO COUTO	9º ANO A	Ativo
14	GUSTAVO BRITO PEREIRA	9º ANO A	Ativo
15	GUSTAVO SOUZA DO PRADO	9º ANO A	Ativo
16	HELLEN ALVES DE SOUZA	9º ANO A	Ativo
17	HELOISA DA COSTA ORTIZ	9º ANO A	Ativo
18	HELOÍSA SILVA DE SOUZA	9º ANO A	Ativo
19	IZABELLA FLOR LINS	9º ANO A	Ativo
20	IZABELY VITÓRIA FERREIRA PORTILHO	9º ANO A	Ativo
21	JOÃO EDUARDO PEREIRA ALEM	9º ANO A	Ativo
22	JOÃO GABRIEL DOS REIS PALMITESTA	9º ANO A	Ativo
23	KAÍKE SILVA DOS SANTOS	9º ANO A	Ativo
24	KARINE BEATRIZ CARVALHO ALVES	9º ANO A	Ativo
25	KAUÃ HENRRIQUE DIAS BARBOSA	9º ANO A	Ativo
26	KAYO BRITO ORTIZ	9º ANO A	Ativo
27	KELVYN HENRIQUE ARAUJO DOS SANTOS	9º ANO A	Ativo
28	KETHELLYN RODRIGUES DA SILVA	9º ANO A	Ativo
29	LAURA COSTA BARBOSA	9º ANO A	Ativo
30	LUCAS LIMA DE ANDRADE	9º ANO A	Ativo
31	LUIZ MIGUEL RODRIGUES ARRUDA	9º ANO A	Ativo
32	LUKAS OLIVEIRA TORRES	9º ANO A	Ativo
33	MARIA EDUARDA OLIVEIRA CORREA	9º ANO A	Ativo
34	MARIAH CRISTINA DOS SANTOS LOPES	9º ANO A	Ativo
35	NICOLAS DOS SANTOS BRUM	9º ANO A	Ativo
36	NINIVY MARTINS DE CAMPOS	9º ANO A	Ativo
37	RAFAEL AUGUSTO LOPES MORETTO	9º ANO A	Ativo
38	SOFIA ORTIZ ARAUJO	9º ANO A	Ativo
39	STHER VITÓRIA CABRAL AQUINO	9º ANO A	Ativo
40	MIGUEL OLIVEIRA DOS SANTOS	9º ANO A	Ativo
41	KAUÃ PORTILHO BRAGA	9º ANO A	Ativo
42	JÚLIA MONTEIRO BENASSI	9º ANO A	Ativo
43	OTÁVIO AUGUSTO DOS SANTOS MACHADO	9º ANO A	Ativo
1	ANA CLARA PAIVA VAZ	1º ANO A	Ativo
2	ANA LUIZA DOS SANTOS BRUM	1º ANO A	Ativo
3	BEATRIZ MALTA DE ALMEIDA FERNANDES VIANA	1º ANO A	Ativo
4	DANIELLA DE ALMEIDA RODRIGUES	1º ANO A	Ativo
5	DAVI ALEXANDRE XAVIER DINIZ	1º ANO A	Ativo
6	FELLIPE FRANCISCO DEGAN DE MIRANDA	1º ANO A	Ativo
7	GABRIELE RORIZ PAES	1º ANO A	Ativo
8	GABRIELLE ALGIMIRO DA SILVA	1º ANO A	Ativo
9	GUSTAVO DOS SANTOS MADIA	1º ANO A	Ativo
10	GUSTAVO HENRIQUE DA SILVA PINHEIRO	1º ANO A	Ativo
11	IZABELLA DA COSTA BARÔA DE CAMARGO	1º ANO A	Ativo
12	JENNIFER MIGUEL ALVES	1º ANO A	Ativo
13	JULIANA DUARTE COENGA	1º ANO A	Ativo
14	JULIA RAMIRO DA SILVA	1º ANO A	Ativo
15	KARLOS RAFAEL DA ROSA SALES	1º ANO A	Ativo
16	LUANNY LAVINIA CEGOVIA DE OLIVEIRA	1º ANO A	Ativo
17	LUCAS GUTIERREZ NICOLAU	1º ANO A	Ativo
18	MANUELLA SANTANA GOMES	1º ANO A	Ativo
19	MARCOS ALBERTO PARENTE LIDIO	1º ANO A	Ativo
20	MARIA GABRIELA LEITE ARAGÃO	1º ANO A	Ativo
21	MARIA JÚLIA DOS SANTOS	1º ANO A	Ativo
22	MATEUS DO NASCIMENTO CUELLAR	1º ANO A	Ativo
23	MATHEUS ALVES BENTO GOMES	1º ANO A	Ativo
24	MIGUEL GUSTAVO BARBOSA COSTA	1º ANO A	Ativo
25	MURILLO SOUZA DA SILVA	1º ANO A	Ativo
26	NICOLAS GABRIEL ARMÔA FERNANDES	1º ANO A	Ativo
27	RAFAEL PINHEIRO PADILHA	1º ANO A	Ativo
28	SARAH SILVA DE OLIVEIRA	1º ANO A	Ativo
29	SOPHIA PONTES DE OLIVEIRA CORREIA	1º ANO A	Ativo
30	VICTOR HUGO BENITEZ	1º ANO A	Ativo
31	VICTOR OLIVEIRA BENITEZ	1º ANO A	Ativo
32	VINÍCIUS KRUK CHAVES	1º ANO A	Ativo
33	VINÍCIUS PEREIRA DE LIMA	1º ANO A	Ativo
34	VITOR HUGO DE CARVALHO PEREIRA RATIER ORTIZ	1º ANO A	Ativo
35	YASMIN SANTANA DE JESUS	1º ANO A	Ativo
36	YASMIN VICTÓRIA IRALA VALENSUELLOS	1º ANO A	Ativo
37	ANNA KETHELING FERNANDES	1º ANO A	Ativo
38	KAUÃ FELIPE JACYNTHO CAVALCANTE	1º ANO A	Ativo
1	ANNA LUIZA RODRIGUES BARROS	1º ANO B	Ativo
2	ANNY KAROLLINY ALMEIDA PARREIRA DA SILVA	1º ANO B	Ativo
3	ANTONHELLA NAZARETH MARCANO LOPEZ	1º ANO B	Ativo
4	BIANCA NILKY MARIANI ARAUJO	1º ANO B	Ativo
5	EDUARDA KAROLYNE MENDES TEIXEIRA	1º ANO B	Ativo
6	ELYSIE SILVA NOGUEIRA	1º ANO B	Ativo
7	EMANUELLY RODRIGUES CRUZ	1º ANO B	Ativo
8	ÉRIK MAZETTI SARAIVA	1º ANO B	Ativo
9	FERNANDA SOUSA DA SILVA	1º ANO B	Ativo
10	GABRIEL DOS SANTOS FARIAS	1º ANO B	Ativo
11	GEOVANNA SILVA BARBOSA	1º ANO B	Ativo
12	GIOVANNA PEREIRA CORREIA DE ARAUJO	1º ANO B	Ativo
13	GUSTAVO MARÇAL ANDRADE	1º ANO B	Ativo
14	ISADORA RODI	1º ANO B	Ativo
15	IVANILDO DOS SANTOS SANTANA	1º ANO B	Ativo
16	IZABELLY AYUMI FRANCO SALVATIERRA	1º ANO B	Ativo
17	JOÃO MADIA	1º ANO B	Ativo
18	JONATHAN ALVES DE ARAUJO	1º ANO B	Ativo
19	JOSÉ OTÁVIO VERISSIMO DA SILVA	1º ANO B	Ativo
20	JULIA VITÓRIA PALAZZINI DE BRITO CARDOSO SANTOS	1º ANO B	Ativo
21	JULLYA OLIVEIRA SILVA	1º ANO B	Ativo
22	KAMILA ALVES DE LEÃO	1º ANO B	Ativo
23	KAMILY VITÓRIA ROCHA AGUILHERA	1º ANO B	Ativo
24	KAUÃ PIETRO RODRIGUES CRUZ	1º ANO B	Ativo
25	MARIA CLARA FERREIRA FOGAÇA	1º ANO B	Ativo
26	MARIA EDUARDA FELIX DE OLIVEIRA	1º ANO B	Ativo
27	MARIA LUIZA ORTELHADO BOMFIM	1º ANO B	Ativo
28	MIGUEL ÂNGELO ROCHA BUSINARO	1º ANO B	Ativo
29	MONIK ALEXANDRA ACOSTA SANTOS	1º ANO B	Ativo
30	PEDRO HENRIQUE MIRANDA RONDON	1º ANO B	Ativo
31	PEDRO ROMOALDO DE MORAES FLORES	1º ANO B	Ativo
32	SARA DE DEUS DA SILVA	1º ANO B	Ativo
33	THALLYS LUAN SALAZAR GOMES	1º ANO B	Ativo
34	THIAGO VILA NOVA	1º ANO B	Ativo
35	WESLEY DE LIMA SOARES	1º ANO B	Ativo
36	YASMIN TOLEDO DE BRITO DUARTE INSFRAN	1º ANO B	Ativo
37	RAPHAELLA FERNANDES CAVALCANTE	1º ANO B	Ativo
1	ABNER KALLEB DE JESUS DIAS	1º ANO C	Ativo
2	ADRIELLY GONÇALVES RODRIGUES	1º ANO C	Ativo
3	ANA CLARA BARBOSA DE BRITO FERREIRA	1º ANO C	Ativo
4	ANA JÚLIA FERELLI PINTO DE OLIVEIRA	1º ANO C	Ativo
5	ARTHUR DANIEL DE SOUZA GARAJO	1º ANO C	Ativo
6	BÁRBARA CILENE SERRA NOSTÓRIO	1º ANO C	Ativo
7	BRUNO ARRUDA MUNIN	1º ANO C	Ativo
8	DANIEL LUCAS MENDES NETO	1º ANO C	Ativo
9	DARA RAYNE DA SILVA ARAUJO	1º ANO C	Ativo
10	DIENIFFER LOARA MELGAREJO CABRAL	1º ANO C	Ativo
11	ELIAS DANIEL LIMA BAPTISTA	1º ANO C	Ativo
12	EMANUELY MEDINA	1º ANO C	Ativo
13	FILIPE ANTÔNIO CASTELO SANCHES	1º ANO C	Ativo
14	GABRIELA DOS SANTOS	1º ANO C	Ativo
15	GABRIELA FERREIRA DE JESUS RIBEIRO	1º ANO C	Ativo
16	HELENA VITÓRIA DE OLIVEIRA PEREIRA	1º ANO C	Ativo
17	INGRID DA COSTA ORTIZ	1º ANO C	Ativo
18	JESUS LUCAS PORTO NOVAIS SOLER	1º ANO C	Ativo
19	JOÃO FELIPE DA SILVA PEDREIRO	1º ANO C	Ativo
20	JOHNNY SAMUEL DE MATTOS RODRIGUES	1º ANO C	Ativo
21	KAIO BRENDOWN MACEDO DE OLIVEIRA SILVA	1º ANO C	Ativo
22	KAIQUE DOS SANTOS BARBOSA	1º ANO C	Ativo
23	LANNA TORRES CABREIRA	1º ANO C	Ativo
24	LUIS HENRIQUE DE OLIVEIRA ARAÚJO	1º ANO C	Ativo
25	MARIA LUIZA ESCOBAR DE SOUSA	1º ANO C	Ativo
26	MARIANE DOS SANTOS ROCHA	1º ANO C	Ativo
27	MARJORIE CASTRO SOLER DE LIMA	1º ANO C	Ativo
28	MICHELLY ELEY DE MOURA SOARES	1º ANO C	Ativo
29	MIKAELLA DE SOUZA CONCEIÇÃO	1º ANO C	Ativo
30	NATALIA DA SILVA PINTO	1º ANO C	Ativo
31	NÍKOLLAS MUNIZ DOS SANTOS	1º ANO C	Ativo
32	QUEMUEL HENRIQUE COSTA EUGENIO	1º ANO C	Ativo
33	RAFAELLA LUCAS DE OLIVEIRA VOLTER	1º ANO C	Ativo
34	RENATA MARION BORGES GUIMARÃES	1º ANO C	Ativo
35	SAMUEL DAVI DOS SANTOS RODRIGUES DA SILVA	1º ANO C	Ativo
36	THAÍSSA GONÇALVES OLAGAS	1º ANO C	Ativo
37	YASMIN ARAÚJO CHARÃO	1º ANO C	Ativo
38	GUSTAVO FERREIRA DA SILVA	1º ANO C	Ativo
1	ALEXANDRE FERRO TEIXEIRA	1º ANO D	Ativo
2	ALINE BELCHIOR DA SILVA AMORIM	1º ANO D	Ativo
3	ANA BEATRIZ CARDOSO MARTINS	1º ANO D	Ativo
4	ANA KARLA NUNES DA SILVA	1º ANO D	Ativo
5	CIBELLY VIEIRA DE BARROS	1º ANO D	Ativo
6	CLAUDIO LUIZ SCHMITT NETO	1º ANO D	Ativo
7	DHIOGO VERÍSSIMO MONTEIRO DOS SANTOS	1º ANO D	Ativo
8	ELDER SILVA DE ASSIS RIBEIRO	1º ANO D	Ativo
9	EMILY GABRIELI GALVÃO MION	1º ANO D	Ativo
10	FELIPE MENDONÇA CAETANO	1º ANO D	Ativo
11	GABRIEL VICENTE DA PAZ SILVA	1º ANO D	Ativo
12	GUILHERME CHAPIESKI CAMPOS	1º ANO D	Ativo
13	GUSTAVO FERREIRA DA SILVA	1º ANO D	Ativo
14	HENRIQUE MOURA ARGUILERA	1º ANO D	Ativo
15	ISABELLY DE SOUZA VIEIRA DOS SANTOS	1º ANO D	Ativo
16	ISABELLY VITÓRIA MENDONÇA FERREIRA	1º ANO D	Ativo
17	IZADORA DE OLIVEIRA FERNANDES	1º ANO D	Ativo
18	JORGE HENRIQUE BRUSAMARELLO DE OLIVEIRA	1º ANO D	Ativo
19	JOSÉ LUIS CONCEIÇÃO DA SILVA	1º ANO D	Ativo
20	JOÃO LUCAS PINHEIRO DE REZENDE	1º ANO D	Ativo
21	JOÃO MARCOS CHAUSTZ BERNARDES	1º ANO D	Ativo
22	JULIA PEIXOTO BONFIM	1º ANO D	Ativo
23	KAMILLY VITÓRIA SIMPLÍCIO ROSA	1º ANO D	Ativo
24	KAUÃ FELIPE JACYNTHO CAVALCANTE	1º ANO D	Ativo
25	LEONARDO LUIZ MONSON DE OLIVEIRA	1º ANO D	Ativo
26	LUCAS MOREIRA RODRIGUES	1º ANO D	Ativo
27	LUIZA MARION BORGES GUIMARÃES	1º ANO D	Ativo
28	MARIA EDUARDA CAMARGO DE MENEZES	1º ANO D	Ativo
29	MIKAEL MENEZES FAGUNDES	1º ANO D	Ativo
30	PEDRO RANDER YULE SILVA	1º ANO D	Ativo
31	PIETRO OTÁVIO DA SILVA MARTINS	1º ANO D	Ativo
32	RENATO SILVA DE JESUS SOUSA	1º ANO D	Ativo
33	REYNAN BATISTA DA SILVA	1º ANO D	Ativo
34	SARA ORTIZ DE SOUZA FERREIRA	1º ANO D	Ativo
35	SOFIA KETLYN CORREA BALIEIRO	1º ANO D	Ativo
36	THAMIRES DOS SANTOS GONÇALVES	1º ANO D	Ativo
38	YASMIM GURGEL DE OLIVEIRA	1º ANO D	Ativo
39	BRUNA LOPES DA CONCEIÇÃO	1º ANO D	Ativo
40	JÚLIA RAMOS PEDREIRO	1º ANO D	Ativo
1	ADRYA VICTÓRIA DE LIMA CALVIS	2º ANO A	Ativo
2	ALESSANDRO MONSON DE OLIVEIRA	2º ANO A	Ativo
3	AMANDA VICTORIA TEIXEIRA ESPINDOLA	2º ANO A	Ativo
4	DAVI PEREIRA MORAES SANTOS	2º ANO A	Ativo
5	DÉRICK EDUARDO DUARTE PAIVA	2º ANO A	Ativo
6	EMANUELLY BEATRIZ CARDOSO DOS SANTOS	2º ANO A	Ativo
7	ERICK HENRIQUE VALEJO DA SILVA	2º ANO A	Ativo
8	GUILHERME CAMPOSANO FAGUNDES	2º ANO A	Ativo
9	GUILHERME GABRIEL CARDENA DE JESUS	2º ANO A	Ativo
10	HENRIQUE RAFAEL DE ALMEIDA FERREIRA	2º ANO A	Ativo
11	JEAN CARLOS NOGUEIRA FONSECA FERREIRA	2º ANO A	Ativo
12	JOAQUIM BARROSO DE ALMEIDA NETO	2º ANO A	Ativo
13	JONATHAN FERREIRA DRUMOND	2º ANO A	Ativo
14	JULIANE RODRIGUES DE SOUSA	2º ANO A	Ativo
15	JULIO CESAR FONSECA MIRANDA JÚNIOR	2º ANO A	Ativo
16	KAYO ENRIK COIMBRA MIRANDA	2º ANO A	Ativo
17	KEYSLER PEREIRA PILENGHI	2º ANO A	Ativo
18	LIDIA VITÓRIA DOS SANTOS FERREIRA	2º ANO A	Ativo
19	LUANA BRITEZ FERREIRA	2º ANO A	Ativo
20	LUÍS HENRICK DOS SANTOS NASCIMENTO	2º ANO A	Ativo
21	LUIZ GUSTAVO GOMES ARCANJO	2º ANO A	Ativo
22	MARIA EDUARDA COUTO BARBOSA	2º ANO A	Ativo
23	NATÁLIA DE SOUZA LIMA	2º ANO A	Ativo
24	PAULO HENRIQUE DO PRADO TEIXEIRA	2º ANO A	Ativo
25	RAFAELY LOHAYNE DE MOURA CARVALHO	2º ANO A	Ativo
26	RIAN ASTOFE MAGALHÂES	2º ANO A	Ativo
27	SAMIRAH GOMES AMARAL	2º ANO A	Ativo
28	SOPHIA VITÓRIA BRUSAMARELLO MORAIS	2º ANO A	Ativo
29	ANNE ELISY CACERES FERREIRA	2º ANO A	Ativo
30	CAROLINE DIAS ALVES	2º ANO A	Ativo
31	LUIZ AUGUSTO ARAUJO JAIME	2º ANO A	Ativo
1	ANNA LUIZA LOURENÇO DA SILVA DE JESUS LUCAS	2º ANO B	Ativo
2	BRENDA VITÓRIA ZAVALA NUNES	2º ANO B	Ativo
3	BRUNO MARCANZONI NONENMACHER	2º ANO B	Ativo
4	CRISTINE AREVALO INHAIA	2º ANO B	Ativo
5	DANIEL AUGUSTO LOPES MORETTO	2º ANO B	Ativo
6	ELLEN SOFIA DE OLIVEIRA DANTAS	2º ANO B	Ativo
7	ELOAH DE LARA PEREIRA	2º ANO B	Ativo
8	FELIPE EMANUEL FRUTUOSO CÁCERES	2º ANO B	Ativo
9	GIOVANNA BATISTA LINO	2º ANO B	Ativo
10	GUILHERME HENRIQUE DOS SANTOS BARBIERO	2º ANO B	Ativo
11	HELOÍSA QUEROBIM JOVELLONE	2º ANO B	Ativo
12	ISABELA AMORIM SANCHEZ	2º ANO B	Ativo
13	ISABELLI BORTOLINI ALVES	2º ANO B	Ativo
14	ISABELLY ORQUÍDEA MARTINS SILVA	2º ANO B	Ativo
15	IZADORA PEREIRA DA SILVA	2º ANO B	Ativo
16	JOÃO VICTOR DA SILVA MORAES	2º ANO B	Ativo
17	KETELLYN DE SOUZA GONÇALVES	2º ANO B	Ativo
18	LEONARDO DE ALMEIDA OLIVEIRA	2º ANO B	Ativo
19	LORENA AUBRY PELEGRINI DO CARMO	2º ANO B	Ativo
20	MARIA ISABEL LEAL DOS SANTOS	2º ANO B	Ativo
21	MARIA JÚLIA SIBEMOL MASCARENHAS BEZERRA	2º ANO B	Ativo
22	MYLENA GABRIELLA VASCONCELOS DA SILVA	2º ANO B	Ativo
23	NADIELLY PRADO DE ALMEIDA	2º ANO B	Ativo
24	PEDRO GUILHERME PEDROZA GOMES	2º ANO B	Ativo
25	PIETTRO CARVALHO SILVA	2º ANO B	Ativo
26	RAONY RIAN DE SOUSA RIBEIRO	2º ANO B	Ativo
27	RAPHAEL DE LARA CORRÊA	2º ANO B	Ativo
28	RAPHAEL DE SOUZA DA SILVA	2º ANO B	Ativo
29	RYAN KAIO FEDERIGI DANTAS	2º ANO B	Ativo
30	SAMARA ORTEGA SILVA	2º ANO B	Ativo
31	SAMIRA ORTEGA SILVA	2º ANO B	Ativo
32	SIBELY FERREIRA MARTINS	2º ANO B	Ativo
33	VICTOR MORAES DOS SANTOS	2º ANO B	Ativo
1	BRAYAN ROCHA PEDREIRO	2º ANO C	Ativo
2	CAUÃ RICARDO FONTOURA PAIM ALMEIDA	2º ANO C	Ativo
3	DIEGO DE OLIVEIRA REGINALDO	2º ANO C	Ativo
4	ELOIZA ALMEIDA DE OLIVEIRA	2º ANO C	Ativo
5	FRED GONÇALVES MARTINS JUNIOR	2º ANO C	Ativo
6	GABRIEL MARQUES CORTES	2º ANO C	Ativo
7	GUSTAVO DE SOUZA SALES	2º ANO C	Ativo
8	GUSTAVO PINHEIRO DA SILVA	2º ANO C	Ativo
9	HAYLLA EMANUELY TORRES DE OLIVEIRA	2º ANO C	Ativo
10	HEITOR SILVA DOS SANTOS	2º ANO C	Ativo
11	KAYKE HENRIQUE CABRAL AQUINO	2º ANO C	Ativo
12	LARYSSA BEATRIZ CORONEL RIBEIRO	2º ANO C	Ativo
13	LEANDRO HENRIQUE KNOPP SILVA	2º ANO C	Ativo
14	LUAN RICARDO SILVA DE OLIVEIRA	2º ANO C	Ativo
15	LUIS FERNANDO OLIVEIRA DA SILVA	2º ANO C	Ativo
16	LUKAS SILVESTRE CHILAVIER	2º ANO C	Ativo
17	MATHEUS VÍTOR SILVA DOS SANTOS	2º ANO C	Ativo
18	MAXUEL DOS SANTOS OLIVEIRA	2º ANO C	Ativo
19	MIGUEL DA SILVA CAVALCANTE	2º ANO C	Ativo
20	MYLLENA DE ALMEIDA ROSARIO	2º ANO C	Ativo
21	NICOLAS SILVA COSTA	2º ANO C	Ativo
22	NICOLLY SENEGAGLEA PINOTTI	2º ANO C	Ativo
23	ORACIO QUINTANA JUNIOR	2º ANO C	Ativo
24	OTÁVIO SILVA DOS SANTOS	2º ANO C	Ativo
25	PEDRO COSTA BARBOSA	2º ANO C	Ativo
26	STELLA RODRIGUES DE SOUSA	2º ANO C	Ativo
27	RENAN ALVES PAZETO	2º ANO C	Ativo
28	RICARDO DE AZEVEDO SCHIPFER DE JESUS	2º ANO C	Ativo
29	THYAGO HENRIQUE SILVA SANTOS	2º ANO C	Ativo
30	PHABLO ROBERTO GAUNA PINHEIRO	2º ANO C	Ativo
1	ALBERT WESKER DA ROSA OLIVEIRA BORGES	3º ANO A	Ativo
2	ALYCE FRANCINE VAZ CARLOS	3º ANO A	Ativo
3	ARTHUR HENRIQUE FURTADO DE ARAUJO	3º ANO A	Ativo
4	BRUNO CESAR BARBOSA DA SILVA	3º ANO A	Ativo
5	CARLOS EDUARDO SOUZA SANTOS	3º ANO A	Ativo
6	CLARA KAORI DE SOUZA HIROTA	3º ANO A	Ativo
7	CLEITON DA SILVA MATOS	3º ANO A	Ativo
8	ESTER VITÓRIA DE LIMA COIMBRA	3º ANO A	Ativo
9	FELIPE MACIEL ROSA	3º ANO A	Ativo
10	FRANCIELI VITÓRIA ROCHA FERREIRA	3º ANO A	Ativo
11	GABRIELA LEMES GOMES	3º ANO A	Ativo
12	GABRIEL SERAFIM SALES	3º ANO A	Ativo
13	HELOISA PEREIRA MARQUES FERREIRA	3º ANO A	Ativo
14	ISABELA CANDIA RODRIGUES MALHEIROS	3º ANO A	Ativo
15	IZABELLA HELLEN DA SILVA	3º ANO A	Ativo
16	KALEL WILLIAN PALHANO LOUREIRO	3º ANO A	Ativo
17	KAUÃ CATELAN NASCIMENTO	3º ANO A	Ativo
18	LEÔNIDAS NUNES DE OLIVEIRA	3º ANO A	Ativo
19	LUCAS GUILHERME DA SILVA SANTOS	3º ANO A	Ativo
20	MANOEL DA SILVA MATOS	3º ANO A	Ativo
21	MIGUEL BARRETO DOS SANTOS	3º ANO A	Ativo
22	NATHÁLIA TOLEDO ROCHA	3º ANO A	Ativo
23	NÁTHALY GOMES DA SILVA	3º ANO A	Ativo
24	PEDRO HENRIQUE SANTOS PEREIRA	3º ANO A	Ativo
25	RENATO VILAS MEDEIROS	3º ANO A	Ativo
26	VINÍCIUS NUNES HADDAD	3º ANO A	Ativo
27	WILLIAM ALVES DE LIMA	3º ANO A	Ativo
28	YASMIM GAMARRA MENDES	3º ANO A	Ativo
29	YASMIN VITÓRIA SANTOS MACEDO	3º ANO A	Ativo
30	LUCIANO LEANDRO	3º ANO A	Ativo
1	ANA LUISA VIANA GERALDI	3º ANO B	Ativo
2	ANGELA CRISTINA DOS SANTOS PACO	3º ANO B	Ativo
3	BRUNO CASTRO LIMA GAUNA	3º ANO B	Ativo
4	DEYVID RYAN MARTINEZ XAVIER	3º ANO B	Ativo
5	EDUARDO BORBA FIGUEIREDO DOS SANTOS	3º ANO B	Ativo
6	ELIMARCOS GODOY FERREIRA	3º ANO B	Ativo
7	ELOAH FERRAZ BRAGA AGUIRRE	3º ANO B	Ativo
8	ESTEVAM RIBEIRO NETO	3º ANO B	Ativo
9	GABRIELE LOURENÇO RAMALHO	3º ANO B	Ativo
10	GUSTAVO MARTINS ALVES DE MELO	3º ANO B	Ativo
11	INGRID CÁCERES GOMES	3º ANO B	Ativo
12	ISADORA HOLANDA CASTILHO	3º ANO B	Ativo
13	JACKELINE RODRIGUES MEDEIROS	3º ANO B	Ativo
14	JENEFER MARIA DE MELO	3º ANO B	Ativo
15	KLARICY FERREIRA DE JESUS RIBEIRO	3º ANO B	Ativo
16	LAUANE VALENTE FERREIRA	3º ANO B	Ativo
17	LUIS FELIPE NOGUEIRA VILLALBA	3º ANO B	Ativo
18	MARIA RHAYSSA PAULINO GOMES	3º ANO B	Ativo
19	MARIA VITÓRIA DIAS DA SILVA	3º ANO B	Ativo
20	MATEUS TEIXEIRA FERREIRA	3º ANO B	Ativo
21	MILLENY PEREIRA DOMINGOS CASTILHO	3º ANO B	Ativo
22	PEDRO HENRIQUE DE OLIVEIRA CAMPOS	3º ANO B	Ativo
23	TAUANY LIMA DE SOUZA	3º ANO B	Ativo
24	THAILYNE VITÓRIA DOS SANTOS	3º ANO B	Ativo
25	VICTOR ESPÍNDOLA ALVES	3º ANO B	Ativo
26	VITOR HUGO VIEIRA SAMBRANA	3º ANO B	Ativo
27	VITOR HUGO VIEIRA SAMBRANA	3º ANO B	Ativo
`;

async function migrate() {
    console.log('Iniciando migração...');
    
    // 1. Buscar turmas existentes
    const turmasRes = await fetch(`${SUPABASE_URL}/rest/v1/turmas?select=id,nome`, {
        headers: { 'apikey': SUPABASE_KEY, 'Authorization': `Bearer ${SUPABASE_KEY}` }
    });
    let turmas = await turmasRes.json();
    console.log(`Encontradas ${turmas.length} turmas no banco.`);

    // 2. Parsear dados da lista
    const lines = rawData.trim().split('\n');
    const studentsToInsert = [];
    const turmasToCreate = new Set();

    for (const line of lines) {
        const [num, nome, turma, status] = line.split('\t');
        if (!turma) continue;
        
        const turmaNomeNorm = turma.trim().toUpperCase();
        turmasToCreate.add(turmaNomeNorm);
        
        studentsToInsert.push({ num: parseInt(num), nome: nome.trim(), turmaNome: turmaNomeNorm, status: status.trim() });
    }

    // 3. Criar turmas que não existem
    for (const tNome of turmasToCreate) {
        if (!turmas.find(t => t.nome.toUpperCase() === tNome)) {
            console.log(`Criando turma: ${tNome}`);
            const createRes = await fetch(`${SUPABASE_URL}/rest/v1/turmas`, {
                method: 'POST',
                headers: { 
                    'apikey': SUPABASE_KEY, 
                    'Authorization': `Bearer ${SUPABASE_KEY}`,
                    'Content-Type': 'application/json',
                    'Prefer': 'return=representation'
                },
                body: JSON.stringify({ nome: tNome, nivel: tNome.includes('ANO') ? 'Fundamental' : 'Médio' })
            });
            const newTurma = await createRes.json();
            turmas.push(newTurma[0]);
        }
    }

    // 4. Preparar alunos para inserção
    const finalAlunos = studentsToInsert.map(s => {
        const turmaObj = turmas.find(t => t.nome.toUpperCase() === s.turmaNome);
        return {
            aluno_numero: s.num,
            nome: s.nome,
            turma_id: turmaObj.id,
            status: 'Ativo'
        };
    });

    // 5. Inserir alunos em lotes (batch)
    console.log(`Inserindo ${finalAlunos.length} alunos...`);
    const insertRes = await fetch(`${SUPABASE_URL}/rest/v1/alunos`, {
        method: 'POST',
        headers: { 
            'apikey': SUPABASE_KEY, 
            'Authorization': `Bearer ${SUPABASE_KEY}`,
            'Content-Type': 'application/json'
        },
        body: JSON.stringify(finalAlunos)
    });

    if (insertRes.ok) {
        console.log('Migração concluída com sucesso!');
    } else {
        const error = await insertRes.json();
        console.error('Erro ao inserir alunos:', error);
    }
}

migrate();
